export const GET_JOBS_LOADING = "GET_JOBS_LOADING";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";

export const ADD_JOBS_LOADING = "ADD_JOBS_LOADING";
export const ADD_JOBS_SUCCESS = "ADD_JOBS_SUCCESS";
export const ADD_JOBS_FAILURE = "ADD_JOBS_FAILURE";

export const SEND_JOB_APPLICATION_LOADING = "SEND_JOB_APPLICATION_LOADING";
export const SEND_JOB_APPLICATION_SUCCESS = "SEND_JOB_APPLICATION_SUCCESS";
export const SEND_JOB_APPLICATION_FAILURE = "SEND_JOB_APPLICATION_FAILURE";

export const MAKE_DECISION_LOADING = "MAKE_DECISION_LOADING";
export const MAKE_DECISION_SUCCESS = "MAKE_DECISION_SUCCESS";
export const MAKE_DECISION_FAILURE = "MAKE_DECISION_FAILURE";

export const GET_JOB_APPLICANTS_LOADING = "GET_JOB_APPLICANTS_LOADING";
export const GET_JOB_APPLICANTS_SUCCESS = "GET_JOB_APPLICANTS_SUCCESS";
export const GET_JOB_APPLICANTS_FAILURE = "GET_JOB_APPLICANTS_FAILURE";

export const GET_RECRUITER_JOBS_LOADING = "GET_RECRUITER_JOBS_LOADING";
export const GET_RECRUITER_JOBS_SUCCESS = "GET_RECRUITER_JOBS_SUCCESS";
export const GET_RECRUITER_JOBS_FAILURE = "GET_RECRUITER_JOBS_FAILURE";
